services:
  database-a:
    container_name: waygo-database
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
      - "33061:33061"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=waygodb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - waygo-network
    healthcheck:
      test: mysql -h localhost -P 3306 -u root -e 'use waygodb;' || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root@waygo-database:3306/waygodb
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      database-a:
        condition: service_healthy
        restart: true
    networks:
      - waygo-network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    networks:
      - waygo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  waygo-network:
    driver: bridge